#pragma once

#define STRINGIZE(s)		STRINGIZE2(s)
#define STRINGIZE2(s)		#s

#define PLUGIN_NAME			Custom Map Loader
#define PLUGIN_NAME_STR		STRINGIZE(PLUGIN_NAME)

#define MAJOR_VERSION		0
#define MINOR_VERSION		1
#define HOTFIX_VERSION		1

#define FULL_VERSION_STRING	"v" STRINGIZE(MAJOR_VERSION) "." STRINGIZE(MINOR_VERSION) "." STRINGIZE(HOTFIX_VERSION)
#define FULL_PLUGIN_NAME	STRINGIZE(PLUGIN_NAME) " v" STRINGIZE(MAJOR_VERSION) "." STRINGIZE(MINOR_VERSION) "." STRINGIZE(HOTFIX_VERSION)
